AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  data-migration-tool-backend

  Sample SAM Template for data-migration-tool-backend

Globals:
  Function:
    Timeout: 30
  Api:
    BinaryMediaTypes:
      - "multipart/form-data"
      - "application/json"

Resources:
  AccessTokensTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AccessTokens
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: platformUrl
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: platformUrl
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  AuthCallbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/callback/
      Handler: app.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        AuthCallbackGET:
          Type: Api
          Properties:
            Path: /callback
            Method: GET
        AuthCallbackPOST:
          Type: Api
          Properties:
            Path: /callback
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AccessTokensTable

  ProcessCSVFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/process-csv/
      Handler: app.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        PostCSV:
          Type: Api
          Properties:
            Path: /process-csv
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AccessTokensTable

  ScanAccessTokenTableFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/scan-access-token-table/
      Handler: app.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        ScanTable:
          Type: Api
          Properties:
            Path: /scan-table
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AccessTokensTable

Outputs:
  AuthCallbackFunction:
    Description: "Auth Callback Function ARN"
    Value: !GetAtt AuthCallbackFunction.Arn

  ProcessCSVFunction:
    Description: "Process CSV Function ARN"
    Value: !GetAtt ProcessCSVFunction.Arn

  ScanAccessTokenTableFunction:
    Description: "Scan Access Token Table Function ARN"
    Value: !GetAtt ScanAccessTokenTableFunction.Arn

  AccessTokensTable:
    Description: "DynamoDB Table for Access Tokens"
    Value: !Ref AccessTokensTable
