AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  data-migration-tool-backend

  Sample SAM Template for data-migration-tool-backend

Globals:
  Api:
    BinaryMediaTypes:
      - "multipart/form-data"
      - "application/json"

# OAuth 2.0 / Authentication Resources
Resources:
  AccessTokensTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AccessTokens
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: platformUrl
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: platformUrl
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  AuthCallbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/callback/
      Handler: app.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        AuthCallbackGET:
          Type: Api
          Properties:
            Path: /callback
            Method: GET
        AuthCallbackPOST:
          Type: Api
          Properties:
            Path: /callback
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AccessTokensTable
      Environment:
        Variables:
          ACCESS_TOKEN_TABLE_NAME: AccessTokens
          CALLBACK_URI: https://jg2x5ta8g1.execute-api.us-east-2.amazonaws.com/Stage/callback
          FRONTEND_URL: http://localhost:3000/callback?access_token=

  ScanAccessTokenTableFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/scan-access-token-table/
      Handler: app.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        ScanTable:
          Type: Api
          Properties:
            Path: /scan-table
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AccessTokensTable

  # -----

  # Data Migration Resources
  DoceboMigrationLogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DoceboMigrationLogTable
      AttributeDefinitions:
        - AttributeName: importId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: importId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: userId-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  DoceboMigrationLogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: docebo-migration-log-bucket

  DoceboDataMigrationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: DoceboDataMigrationQueue

  CSVHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/csv-handler/
      Handler: app.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        PostCsv:
          Type: Api
          Properties:
            Path: /post-csv
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DoceboMigrationLogTable
        - Statement:
            Effect: Allow
            Action:
              - sqs:SendMessage
            Resource: !GetAtt DoceboDataMigrationQueue.Arn
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref DoceboDataMigrationQueue
          MIGRATION_LOG_TABLE: !Ref DoceboMigrationLogTable
          MIGRATION_LOG_S3_BUCKET: !Ref DoceboMigrationLogBucket

  ChunkHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/chunk-handler/
      Handler: app.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt DoceboDataMigrationQueue.Arn
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AccessTokensTable
        - DynamoDBCrudPolicy:
            TableName: !Ref DoceboMigrationLogTable
        - Statement:
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
            Resource: !Sub arn:aws:s3:::${DoceboMigrationLogBucket}/*
        - Statement:
            Effect: Allow
            Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Resource: !GetAtt DoceboDataMigrationQueue.Arn
      Environment:
        Variables:
          SQS_QUEUE_URL: !Ref DoceboDataMigrationQueue
          MIGRATION_LOG_TABLE: !Ref DoceboMigrationLogTable
          ACCESS_TOKEN_TABLE_NAME: AccessTokens
          MIGRATION_LOG_S3_BUCKET: !Ref DoceboMigrationLogBucket

Outputs:
  AccessTokensTable:
    Description: "DynamoDB Table for Access Tokens"
    Value: !Ref AccessTokensTable

  AuthCallbackUrl:
    Description: "API Gateway endpoint URL for the Auth Callback function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/callback"

  ScanAccessTokenTableUrl:
    Description: "API Gateway endpoint URL for the Scan Access Token Table function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/scan-table"

  PostCSVUrl:
    Description: "API Gateway endpoint URL for the main handler function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/post-csv"

  DoceboMigrationLogTable:
    Description: "DynamoDB Table for Docebo Migration Logs"
    Value: !Ref DoceboMigrationLogTable

  DoceboMigrationLogBucket:
    Description: "S3 Bucket for Docebo Migration Logs"
    Value: !Ref DoceboMigrationLogBucket

  DoceboDataMigrationQueue:
    Description: "SQS Queue for Docebo Data Migration"
    Value: !Ref DoceboDataMigrationQueue

  CSVHandlerFunction:
    Description: "Main CSV Handler Lambda Function ARN"
    Value: !GetAtt CSVHandlerFunction.Arn

  ChunkHandlerFunction:
    Description: "Auxiliary Chunk Handler Lambda Function ARN"
    Value: !GetAtt ChunkHandlerFunction.Arn
