AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  data-migration-tool-backend

  Sample SAM Template for data-migration-tool-backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    LoggingConfig:
      LogFormat: JSON
  Api:
    BinaryMediaTypes:
      - "multipart/form-data"
      - "application/json"
Resources:
  AuthCallbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/callback/
      Handler: app.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        AuthCallbackGET:
          Type: Api
          Properties:
            Path: /callback
            Method: GET
        AuthCallbackPOST:
          Type: Api
          Properties:
            Path: /callback
            Method: POST
  ProcessCSVFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/process-csv/
      Handler: app.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        PostCSV:
          Type: Api
          Properties:
            Path: /process-csv
            Method: POST
